name: flutter_fab_dialer
description: Flutter plugin for using a Fab Dialer / Fab Speed Dial to use it as a menu.
 It uses material design library as the FAB is originated from Android.
version: 0.1.1
author: Leondev7 <leondev7jgt@gmail.com>
homepage: https://github.com/Leondev7/flutter_fab_dialer

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.3

environment:
  sdk: ">=2.0.0 <3.0.0"